name: Publish release
on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build fat Jar with Gradle
        run: ./gradlew shadowJar
      - name: Create tar.gz package of the application
        run: ./package.sh
      - name: Upload tar.gz package to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: bakup.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove src directory for makepkg
        run: rm -r ./src
      - name: Build Arch Linux package with makepkg
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
      - name: Upload Arch Linux package to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.makepkg.outputs.pkgfile0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
