name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests with Gradle
        run: ./gradlew test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build fat Jar with Gradle
        run: ./gradlew shadowJar
      - name: Upload fat JAR
        uses: actions/upload-artifact@v2
        with:
          name: bakup.jar
          path: build/libs/bakup.jar